version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ipl_prediction
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd django_backend &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/ipl_prediction
      - DEBUG=1

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd fastapi_backend &&
             uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/ipl_prediction

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  postgres_data:
  ollama_data:
